//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistantBroadcasts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssistantBroadcasts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts.
        /// </summary>
        internal static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complete authorization in the browser and enter the resulting code at the end.
        /// </summary>
        internal static string authorize {
            get {
                return ResourceManager.GetString("authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban user.
        /// </summary>
        internal static string ban_user {
            get {
                return ResourceManager.GetString("ban_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Embedded bot accounts (needs restart chat).
        /// </summary>
        internal static string bot_accounts {
            get {
                return ResourceManager.GetString("bot_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use for GoodGame.
        /// </summary>
        internal static string bot_gg {
            get {
                return ResourceManager.GetString("bot_gg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use for Twitch.
        /// </summary>
        internal static string bot_twitch {
            get {
                return ResourceManager.GetString("bot_twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chance random quotes (250 = 25%).
        /// </summary>
        internal static string chance_random_quotes {
            get {
                return ResourceManager.GetString("chance_random_quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chats.
        /// </summary>
        internal static string chats {
            get {
                return ResourceManager.GetString("chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опять работа?!
        ///Вам меня не жалко?
        ///Ну вот, меня убьют.
        ///Работа не волк, в лес не убежит.
        ///Мы поймали ведьму, можно мы её сожжём?
        ///Мне неведом страх. Моё сердце жаждет битвы.
        ///Да свершится правосудие! Во имя света!
        ///Гоблин в доспехах — консервы «Завтрак дракона».
        ///Добро, добро. Боги зрят благосклонно, мир очищается от скверны.
        ///Ваша возня мешает мне сосредоточиться!
        ///Если вы не оставите меня в покое, я превращу вас в безмозглую овцу!
        ///И солнце ярко блещет, И веселей пейзаж, Когда в желудке плещется C2H5OH!! [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string citations_list {
            get {
                return ResourceManager.GetString("citations_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear list.
        /// </summary>
        internal static string clear_list {
            get {
                return ResourceManager.GetString("clear_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command*.
        /// </summary>
        internal static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        internal static string default_ {
            get {
                return ResourceManager.GetString("default_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные команды:.
        /// </summary>
        internal static string default_help {
            get {
                return ResourceManager.GetString("default_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.
        /// </summary>
        internal static string default_icon {
            get {
                return ResourceManager.GetString("default_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключен..
        /// </summary>
        internal static string default_offline {
            get {
                return ResourceManager.GetString("default_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sleep this pleasure..
        /// </summary>
        internal static string default_sleep {
            get {
                return ResourceManager.GetString("default_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приветствуем новых подписчиков.
        /// </summary>
        internal static string default_welcome_followers_text {
            get {
                return ResourceManager.GetString("default_welcome_followers_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поприветствуем нового премиум подписчика.
        /// </summary>
        internal static string default_welcome_subscribers_text {
            get {
                return ResourceManager.GetString("default_welcome_subscribers_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete message.
        /// </summary>
        internal static string del_message {
            get {
                return ResourceManager.GetString("del_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game.
        /// </summary>
        internal static string dfi_game {
            get {
                return ResourceManager.GetString("dfi_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last.FM.
        /// </summary>
        internal static string dfi_lastfm {
            get {
                return ResourceManager.GetString("dfi_lastfm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random Username.
        /// </summary>
        internal static string dfi_random_username {
            get {
                return ResourceManager.GetString("dfi_random_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Char separator for responses.
        /// </summary>
        internal static string dfi_separator {
            get {
                return ResourceManager.GetString("dfi_separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uptime.
        /// </summary>
        internal static string dfi_uptime {
            get {
                return ResourceManager.GetString("dfi_uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        internal static string dfi_username {
            get {
                return ResourceManager.GetString("dfi_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VKontakte.
        /// </summary>
        internal static string dfi_vk {
            get {
                return ResourceManager.GetString("dfi_vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alerts.
        /// </summary>
        internal static string ed_alerts {
            get {
                return ResourceManager.GetString("ed_alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commands.
        /// </summary>
        internal static string ed_commands {
            get {
                return ResourceManager.GetString("ed_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Labels.
        /// </summary>
        internal static string ed_labels {
            get {
                return ResourceManager.GetString("ed_labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quests.
        /// </summary>
        internal static string ed_quests {
            get {
                return ResourceManager.GetString("ed_quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spells.
        /// </summary>
        internal static string ed_spells {
            get {
                return ResourceManager.GetString("ed_spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Elements.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File random quotes.
        /// </summary>
        internal static string file_random_quotes {
            get {
                return ResourceManager.GetString("file_random_quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoodGame.
        /// </summary>
        internal static string goodgame {
            get {
                return ResourceManager.GetString("goodgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoodGame Bot.
        /// </summary>
        internal static string goodgame_bot {
            get {
                return ResourceManager.GetString("goodgame_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;Main&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;
        ///			}
        ///			.channel { 
        ///				margin-top: 5px;
        ///				padding: 5px;				
        ///			}
        ///			.channel:hover { 
        ///			 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string goodgame_favorite {
            get {
                return ResourceManager.GetString("goodgame_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;Twitch Now&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;				
        ///			}			
        ///			a {
        ///				text-decoration: none;
        ///				outline: none;
        ///				font-family: &apos;Open  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string goodgame_games {
            get {
                return ResourceManager.GetString("goodgame_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;GoodGame Now&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;
        ///			}
        ///			.channel { 
        ///				margin-top: 5px;
        ///				padding: 5px;				
        ///			}
        ///			.channel:hover [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string goodgame_now {
            get {
                return ResourceManager.GetString("goodgame_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello follower.
        /// </summary>
        internal static string hello_follower {
            get {
                return ResourceManager.GetString("hello_follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello premium.
        /// </summary>
        internal static string hello_premium {
            get {
                return ResourceManager.GetString("hello_premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possible options for input:
        ///Miker - the name of the channel;
        ///#612 - id of channel;
        ///#r12 - id of room
        ///$1535 - id of cup..
        /// </summary>
        internal static string help_channel {
            get {
                return ResourceManager.GetString("help_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text in auto-help.
        /// </summary>
        internal static string help_cmd {
            get {
                return ResourceManager.GetString("help_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -----Команды-----
        ///
        ///Стандартные команды:
        ///!help - выводит список команд, кроме тех которые отмечены скрытыми, доступна всем;
        ///!bot_sleep - отправляет бота в сон и оповещает сообщением, которое можно изменить в настройках, доступна стримерам, помощникам и модератором.
        ///!quest - команда нужная для работы заданий, не рекомендуется ее переназначать.
        ///
        ///Стандартные команды можно переназначить для этого нужно создать новую команду со стандартным именем и, например, нужным текстом.
        ///
        ///Если список содержит две ком [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_commands {
            get {
                return ResourceManager.GetString("help_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -----Заметки-----
        ///
        ///Имена файлов соответствуют именам заметок.
        ///Файлы заметок сохраняются в папке
        ///C:\Users\&lt;Имя пользователя&gt;\Documents\Assistant Broadcasts
        ///
        ///Если список содержит две заметки с одинаковым именем, то в файл запишутся данные той которая ниже по списку.
        ///
        ///Управлять позицией в списке можно с помощью стрелок в правом нижнем углу. Там же есть кнопка для переключения отображения между именем и описанием..
        /// </summary>
        internal static string help_labels {
            get {
                return ResourceManager.GetString("help_labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Respond to command !help in PM.
        /// </summary>
        internal static string help_pm {
            get {
                return ResourceManager.GetString("help_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -----Задания-----
        ///
        ///!quest - возвращает в пм первый вопрос и его ключ.
        ///!quest &lt;ключ вопроса&gt; - получение текста вопроса, возвращает вопрос и ключ.
        ///!quest &lt;ключ вопроса&gt; &lt;ответ на вопрос&gt; - ответ на вопрос, если ответ правильный - следующий вопрос с ключем, иначе сообщение о неверном ответе или подсказку.
        ///
        ///Если пользователь ответил на последний вопрос, то бот сообщает в чат об этом.
        ///
        ///Ответ на вопрос не должен содержать пробелы, при этом поле ответ может содержать регулярное выражение.
        ///
        ///Управлять поз [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string help_quests {
            get {
                return ResourceManager.GetString("help_quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular Expressions .NET Framework
        ///The regular expression pattern (Mr\.? |Mrs\.? |Miss |Ms\.? ) 
        ///matches any occurrence of &quot;Mr &quot;, &quot;Mr. &quot;, &quot;Mrs &quot;, &quot;Mrs. &quot;, &quot;Miss &quot;, &quot;Ms or &quot;Ms. &quot;.
        /// </summary>
        internal static string help_regex_net {
            get {
                return ResourceManager.GetString("help_regex_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide in auto-help.
        /// </summary>
        internal static string hide_in_autohelp {
            get {
                return ResourceManager.GetString("hide_in_autohelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_downward_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_downward_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_upward_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_upward_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_casino_black_18dp {
            get {
                object obj = ResourceManager.GetObject("ic_casino_black_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_close_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_close_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_description_black_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_description_black_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_exit_to_app_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_exit_to_app_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_favorite_goodgame_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_favorite_goodgame_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_favorite_twitch_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_favorite_twitch_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_info_outline_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_info_outline_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_launch_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_launch_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_refresh_white_36dp {
            get {
                object obj = ResourceManager.GetObject("ic_refresh_white_36dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_goodgame_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_star_goodgame_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_star_twitch_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_star_twitch_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_videogame_asset_goodgame_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_videogame_asset_goodgame_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_videogame_asset_twitch_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_videogame_asset_twitch_48dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icon message GG.
        /// </summary>
        internal static string icon_cmd {
            get {
                return ResourceManager.GetString("icon_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap id_channel_vidi {
            get {
                object obj = ResourceManager.GetObject("id_channel_vidi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignore registr.
        /// </summary>
        internal static string ignore_registr {
            get {
                return ResourceManager.GetString("ignore_registr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert.
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count elements.
        /// </summary>
        internal static string label_count {
            get {
                return ResourceManager.GetString("label_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description*.
        /// </summary>
        internal static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element.
        /// </summary>
        internal static string label_element {
            get {
                return ResourceManager.GetString("label_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Label.
        /// </summary>
        internal static string label_label {
            get {
                return ResourceManager.GetString("label_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show elements as list.
        /// </summary>
        internal static string label_list {
            get {
                return ResourceManager.GetString("label_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name*.
        /// </summary>
        internal static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time period.
        /// </summary>
        internal static string label_time {
            get {
                return ResourceManager.GetString("label_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string label_type {
            get {
                return ResourceManager.GetString("label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last update.
        /// </summary>
        internal static string last_update {
            get {
                return ResourceManager.GetString("last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LastFM.
        /// </summary>
        internal static string lastfm {
            get {
                return ResourceManager.GetString("lastfm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Getting audio track on last.fm.
        /// </summary>
        internal static string lastfm_get {
            get {
                return ResourceManager.GetString("lastfm_get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account last.fm .
        /// </summary>
        internal static string lastfm_text {
            get {
                return ResourceManager.GetString("lastfm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assistant Broadcasts.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not required.
        /// </summary>
        internal static string not_required {
            get {
                return ResourceManager.GetString("not_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object is already at the bottom or is not selected.
        /// </summary>
        internal static string notifi_list_bottom {
            get {
                return ResourceManager.GetString("notifi_list_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object is not selected.
        /// </summary>
        internal static string notifi_list_not_selected {
            get {
                return ResourceManager.GetString("notifi_list_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object is already at the top or is not selected.
        /// </summary>
        internal static string notifi_list_top {
            get {
                return ResourceManager.GetString("notifi_list_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all required fields are filled..
        /// </summary>
        internal static string notifi_required_fields {
            get {
                return ResourceManager.GetString("notifi_required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notice of beginning favorites.
        /// </summary>
        internal static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close window.
        /// </summary>
        internal static string now_close_window {
            get {
                return ResourceManager.GetString("now_close_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit the application.
        /// </summary>
        internal static string now_exit_app {
            get {
                return ResourceManager.GetString("now_exit_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now favorite channels on GoodGame.RU.
        /// </summary>
        internal static string now_favorites_goodgame {
            get {
                return ResourceManager.GetString("now_favorites_goodgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now favorite channels on Twitch.TV.
        /// </summary>
        internal static string now_favorites_twitch {
            get {
                return ResourceManager.GetString("now_favorites_twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now top games on GoodGame.RU.
        /// </summary>
        internal static string now_games_goodgame {
            get {
                return ResourceManager.GetString("now_games_goodgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now top games on Twitch.TV.
        /// </summary>
        internal static string now_games_twitch {
            get {
                return ResourceManager.GetString("now_games_twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh the current page.
        /// </summary>
        internal static string now_refresh_page {
            get {
                return ResourceManager.GetString("now_refresh_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swap to main.
        /// </summary>
        internal static string now_swap_to_main {
            get {
                return ResourceManager.GetString("now_swap_to_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now top channels on GoodGame.RU.
        /// </summary>
        internal static string now_top_goodgame {
            get {
                return ResourceManager.GetString("now_top_goodgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Watch now top channels on Twitch.TV.
        /// </summary>
        internal static string now_top_twitch {
            get {
                return ResourceManager.GetString("now_top_twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message when offline.
        /// </summary>
        internal static string offline_cmd {
            get {
                return ResourceManager.GetString("offline_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assistants.
        /// </summary>
        internal static string only_assistant {
            get {
                return ResourceManager.GetString("only_assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Premiums.
        /// </summary>
        internal static string only_premium {
            get {
                return ResourceManager.GetString("only_premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streamers.
        /// </summary>
        internal static string only_streamer {
            get {
                return ResourceManager.GetString("only_streamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        internal static string only_users {
            get {
                return ResourceManager.GetString("only_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список изменений:
        ///
        ///Версия 0.2
        ///- Исправлены ошибки связанные с twitch
        ///- Доработано окно добавления/изменения заметок
        ///- Добавлена возможность установливать кастомные каналы чатов
        ///- Изменена работа иконки в трее, теперь по ПКМ доступно меню с возможностью выбора что открыть watch now или основное окно
        ///- Watch Now теперь можно открыть через меню
        ///- Элемент команды {random_username} теперь при совпадение ника или при пустом списке пользователей заменяеться на &quot;Неизвестный&quot;
        ///
        ///
        ///Версия 0.1
        ///- Бета версия
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string patches {
            get {
                return ResourceManager.GetString("patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permissions.
        /// </summary>
        internal static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chance hint.
        /// </summary>
        internal static string quest_chance {
            get {
                return ResourceManager.GetString("quest_chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quest description.
        /// </summary>
        internal static string quest_description {
            get {
                return ResourceManager.GetString("quest_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hint when the wrong response.
        /// </summary>
        internal static string quest_hint {
            get {
                return ResourceManager.GetString("quest_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Secret name.
        /// </summary>
        internal static string quest_name {
            get {
                return ResourceManager.GetString("quest_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quest response.
        /// </summary>
        internal static string quest_response {
            get {
                return ResourceManager.GetString("quest_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are really want to clean list of objects?.
        /// </summary>
        internal static string question_clean {
            get {
                return ResourceManager.GetString("question_clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are really want to set default value?.
        /// </summary>
        internal static string question_default {
            get {
                return ResourceManager.GetString("question_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are really want to delete object?.
        /// </summary>
        internal static string question_delete {
            get {
                return ResourceManager.GetString("question_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable the Russian language?.
        /// </summary>
        internal static string question_ru_lang {
            get {
                return ResourceManager.GetString("question_ru_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random quotes.
        /// </summary>
        internal static string random_quotes {
            get {
                return ResourceManager.GetString("random_quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regex .Net.
        /// </summary>
        internal static string regex_net {
            get {
                return ResourceManager.GetString("regex_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * - required fields.
        /// </summary>
        internal static string required_fields {
            get {
                return ResourceManager.GetString("required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset language.
        /// </summary>
        internal static string reset_lang {
            get {
                return ResourceManager.GetString("reset_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language changes after a reboot app.
        /// </summary>
        internal static string reset_lang_help {
            get {
                return ResourceManager.GetString("reset_lang_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Response.
        /// </summary>
        internal static string response {
            get {
                return ResourceManager.GetString("response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Response to file.
        /// </summary>
        internal static string response_file {
            get {
                return ResourceManager.GetString("response_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save all.
        /// </summary>
        internal static string save_all {
            get {
                return ResourceManager.GetString("save_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save to file.
        /// </summary>
        internal static string save_file {
            get {
                return ResourceManager.GetString("save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search:.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send in pm.
        /// </summary>
        internal static string send_in_pm {
            get {
                return ResourceManager.GetString("send_in_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show descriptions.
        /// </summary>
        internal static string show_descritions {
            get {
                return ResourceManager.GetString("show_descritions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show names.
        /// </summary>
        internal static string show_names {
            get {
                return ResourceManager.GetString("show_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message when on/off sleep.
        /// </summary>
        internal static string sleep_cmd {
            get {
                return ResourceManager.GetString("sleep_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start page.
        /// </summary>
        internal static string start_page {
            get {
                return ResourceManager.GetString("start_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System logs.
        /// </summary>
        internal static string sys_logs {
            get {
                return ResourceManager.GetString("sys_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 30 day.
        /// </summary>
        internal static string time_30day {
            get {
                return ResourceManager.GetString("time_30day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string time_all {
            get {
                return ResourceManager.GetString("time_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom.
        /// </summary>
        internal static string time_custom {
            get {
                return ResourceManager.GetString("time_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last.
        /// </summary>
        internal static string time_last {
            get {
                return ResourceManager.GetString("time_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monthly.
        /// </summary>
        internal static string time_monthly {
            get {
                return ResourceManager.GetString("time_monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session.
        /// </summary>
        internal static string time_session {
            get {
                return ResourceManager.GetString("time_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekly.
        /// </summary>
        internal static string time_weekly {
            get {
                return ResourceManager.GetString("time_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitch.
        /// </summary>
        internal static string twitch {
            get {
                return ResourceManager.GetString("twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitch Bot.
        /// </summary>
        internal static string twitch_bot {
            get {
                return ResourceManager.GetString("twitch_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twitch_code {
            get {
                object obj = ResourceManager.GetObject("twitch_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;Twitch Now&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;
        ///			}
        ///			.channel { 
        ///				margin-top: 5px;
        ///				padding: 5px;						
        ///			}
        ///			.channel:hover [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string twitch_favorite {
            get {
                return ResourceManager.GetString("twitch_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;Twitch Now&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;				
        ///			}			
        ///			a {
        ///				text-decoration: none;
        ///				outline: none;
        ///				font-family: &apos;Open  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string twitch_games {
            get {
                return ResourceManager.GetString("twitch_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;/&gt;
        ///		&lt;title&gt;Twitch Now&lt;/title&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;https://code.jquery.com/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///		&lt;style&gt;  
        ///			body {
        ///				margin: 0px;
        ///				width: 350px;
        ///				font-family: &apos;Open Sans&apos;, sans-serif;
        ///				color: #b8d5ff;	
        ///				background-color: #0D1221;
        ///			}
        ///			.channel { 
        ///				margin-top: 5px;
        ///				padding: 5px;						
        ///			}
        ///			.channel:hover [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string twitch_now {
            get {
                return ResourceManager.GetString("twitch_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Twitch Private.
        /// </summary>
        internal static string twitch_private {
            get {
                return ResourceManager.GetString("twitch_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate.
        /// </summary>
        internal static string type_donate {
            get {
                return ResourceManager.GetString("type_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Donate Top.
        /// </summary>
        internal static string type_donate_top {
            get {
                return ResourceManager.GetString("type_donate_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Followers.
        /// </summary>
        internal static string type_followers {
            get {
                return ResourceManager.GetString("type_followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subscribers.
        /// </summary>
        internal static string type_subscride {
            get {
                return ResourceManager.GetString("type_subscride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unknown.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vidi.
        /// </summary>
        internal static string vidi {
            get {
                return ResourceManager.GetString("vidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VKontakte.
        /// </summary>
        internal static string vkontakte {
            get {
                return ResourceManager.GetString("vkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Media vote.
        /// </summary>
        internal static string vote_media {
            get {
                return ResourceManager.GetString("vote_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome new followers GG.
        /// </summary>
        internal static string welcome_followers {
            get {
                return ResourceManager.GetString("welcome_followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text in greeting new followers.
        /// </summary>
        internal static string welcome_followers_text {
            get {
                return ResourceManager.GetString("welcome_followers_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome new subscribers GG.
        /// </summary>
        internal static string welcome_subscribers {
            get {
                return ResourceManager.GetString("welcome_subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text in greeting new subscribers.
        /// </summary>
        internal static string welcome_subscribers_text {
            get {
                return ResourceManager.GetString("welcome_subscribers_text", resourceCulture);
            }
        }
    }
}
